SELECT `image_analysis_errors`.`id`,
    `image_analysis_errors`.`file_id`,
    `image_analysis_errors`.`error_message`,
    `image_analysis_errors`.`error_timestamp`
FROM `File_Deduplification`.`image_analysis_errors`;

SELECT `image_exif_raw`.`id`,
    `image_exif_raw`.`image_metadata_id`,
    `image_exif_raw`.`exif_tag`,
    `image_exif_raw`.`exif_value`
FROM `File_Deduplification`.`image_exif_raw`;

SELECT `image_keywords`.`id`,
    `image_keywords`.`image_metadata_id`,
    `image_keywords`.`keyword`
FROM `File_Deduplification`.`image_keywords`;

SELECT `image_metadata`.`id`,
    `image_metadata`.`file_id`,
    `image_metadata`.`width`,
    `image_metadata`.`height`,
    `image_metadata`.`format`,
    `image_metadata`.`mode`,
    `image_metadata`.`color_space`,
    `image_metadata`.`dpi_x`,
    `image_metadata`.`dpi_y`,
    `image_metadata`.`bit_depth`,
    `image_metadata`.`has_transparency`,
    `image_metadata`.`camera_make`,
    `image_metadata`.`camera_model`,
    `image_metadata`.`lens_make`,
    `image_metadata`.`lens_model`,
    `image_metadata`.`date_taken`,
    `image_metadata`.`date_digitized`,
    `image_metadata`.`date_modified`,
    `image_metadata`.`iso_speed`,
    `image_metadata`.`exposure_time`,
    `image_metadata`.`f_number`,
    `image_metadata`.`focal_length`,
    `image_metadata`.`flash`,
    `image_metadata`.`white_balance`,
    `image_metadata`.`metering_mode`,
    `image_metadata`.`exposure_program`,
    `image_metadata`.`exposure_bias`,
    `image_metadata`.`gps_latitude`,
    `image_metadata`.`gps_longitude`,
    `image_metadata`.`gps_altitude`,
    `image_metadata`.`gps_timestamp`,
    `image_metadata`.`gps_location_name`,
    `image_metadata`.`copyright`,
    `image_metadata`.`creator`,
    `image_metadata`.`credit`,
    `image_metadata`.`caption`,
    `image_metadata`.`title`,
    `image_metadata`.`software`,
    `image_metadata`.`orientation`,
    `image_metadata`.`compression`,
    `image_metadata`.`quality`,
    `image_metadata`.`rating`,
    `image_metadata`.`file_created`,
    `image_metadata`.`file_modified`,
    `image_metadata`.`analyzed_at`,
    `image_metadata`.`analysis_version`,
    `image_metadata`.`has_errors`
FROM `File_Deduplification`.`image_metadata`;
